### ISSUE TITLE
Error "can't execute perl"

### ISSUE THREAD

**Issue by mallikarjun-sidveer** [stamer/texmlbus#1]
Getting below error when we try to Latex manuscript to XML.
env: can't execute 'perl
': No such file or directory
we are using windows, do we need to install anything like 'perl' and need to set path.

**Comment by stamer** [comment]
You do not need to install perl on the windows machine, everything is running inside the containers.
Do you try to do the conversion via the web interface or somewhere else?

Have you followed  the instructions as given below?
1. git clone --recursive https://github.com/stamer/texmlbus.git
2. cd texmlbus
3. git submodule update --init --recursive
4. docker-compose up

You might want to try a `docker-composer build` between steps 3 and 4 to make sure all containers are built. Do you see any other error messages in the output of docker-compose?
Are you using wsl1 or wsl2?

**Comment by mallikarjun-sidveer** [comment]
Yes, We followed above steps. 
Below error we are betting after executing "docker-compose up" command.

texmlbus_1       | # worker:22 SSH-2.0-OpenSSH_8.1
texmlbus_1       | # worker:22 SSH-2.0-OpenSSH_8.1
texmlbus_1       | # worker:22 SSH-2.0-OpenSSH_8.1
texmlbus_1       | chmod articles...
texmlbus_1       | chmod articles/upload...
texmlbus_1       | chmod: /srv/texmlbus/articles/upload: No such file or directo
ry
texmlbus_1       | mkdir: can't create directory '/opt/run': File exists
texmlbus_1       | Composer could not find a composer.json file in /srv/texmlbus
/build
texmlbus_1       | To initialize a project, please create a composer.json file a
s described in the https://getcomposer.org/ "Getting Started" section
texmlbus_1       | Clearing any old processes...
texmlbus_1       | Starting apache...
texmlbus_1       | AH00526: Syntax error on line 244 of /etc/apache2/httpd.conf:

texmlbus_1       | DocumentRoot '/srv/texmlbus/build/server/htdocs' is not a dir
ectory, or is not readable
texmlbus_1       | Could not open input file: /srv/texmlbus/build/dmake/texmlbus
.php
texmlbus_texmlbus_1 exited with code 1

**Comment by stamer** [comment]
As you can see on line 48 and 49 of docker-compose.yml, two volumes are mounted inside your current tree, but you are not able to access these directories. `volumes/articles` will be created when the container is created, but `volumes/build` is the actual source code.
Maybe you have not shared your drive, so you are unable to mount these volumes (see explanation on main page). 
You have mentioned that you are using Windows 7, therefore I assume you are using Docker Toolbox or Docker Machine, which are both legacy and outdated products. I think the easiest way to solve your problem is to update to a more recent OS. You can then use Docker Desktop (Windows or Mac), or a recent version of Docker Engine (Linux). I am quite sure that the problem will vanish then.

**Comment by stamer** [comment]
Is the problem resolved? I do not have Windows 7 and therefore unable to test in that environment.

**Comment by stamer** [comment]
I have tested different setups on Windows 10 (wsl1 and wsl2) and Linux. Everything is fine, therefore I close this issue now. Older docker versions (Docker Toolbox, Docker Machine) for Windows 7 are not supported, as they are not testable and legacy products.
